version: '3.8'

services:
  web:
    image: python:3.9-slim
    container_name: flask_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
